apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcomebot-master
spec:
  template:
    spec:
      containers:
      - name: master
        env:
        # Production log level
        - name: LOG_LEVEL
          value: "info"
        
        # PostgreSQL with SSL in production
        - name: POSTGRES_SSLMODE
          value: "require"
        
        # Production-specific resources (high availability)
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"

