apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcomebot-worker
spec:
  replicas: 3  # 3 workers for production (can scale up)
  template:
    spec:
      containers:
      - name: worker
        env:
        # Production log level
        - name: LOG_LEVEL
          value: "info"
        
        # PostgreSQL with SSL in production
        - name: POSTGRES_SSLMODE
          value: "require"
        
        # Production-specific resources
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

