apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcomebot-master
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: master
          image: harbor.morikuma.org/welcomebot/welcomebot-master:lightprod
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "json"
            - name: POSTGRES_SSLMODE
              value: "disable"
            # Override Redis Sentinel config with simple Redis
            - name: REDIS_SENTINEL_ADDRS
              value: ""
            - name: REDIS_MASTER_NAME
              value: ""
            - name: REDIS_ADDR
              value: "redis-service:6379"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

